### PR TITLE
Always check host against SSLHOST to redirect if doesn't match

### PR DESCRIPTION
**Pull request by aek**

### CODE REVIEW

**Comment by unrolled** [comment]
Hey @aek, I think we are going to need a new config setting to make this happen. If we merge this change, it could break functionality for existing users of the package. Lets add a new config setting called `SSLForceHost`. Default it to false, but if true do the proper check that's in the PR.

**Comment by aek** [comment]
Hi @unrolled I have committed those changes but the Travis jobs are failing without errors, or at least I don't see it. Could you check what could be happening?
Thanks

**Comment by unrolled** [comment]
It's that darn `gometalinter`... The error is `secure.go:38:14:warning: struct of size 192 could be 184 (maligned)`. You'll need to move the `SSLForceHost bool` up with the other bools. I'm not sure I like that rule... though it's supposed to make for more efficient compiling. ¯\_(ツ)_/¯

**Comment by aek** [comment]
Could be this warning?
secure.go:38:14:warning: struct of size 192 could be 184 (maligned)

**Comment by aek** [comment]
It was exactly that. Good to know it, I'm still new to Golang and it's code conventions and tools

**Comment by aek** [comment]
As you suggest I left the exact original code working and add the new option processing to handle the scenarios not covered by the SSLRedirect due to the request already with SSL

**Comment by aek** [comment]
Done. I have added a few tests and seems that have passed ok

- TestSSLForceHostWithHTTPS
- TestSSLForceHostWithHTTP
- TestSSLForceHostWithSSLRedirect
- TestSSLForceHostTemporaryRedirect

**Comment by unrolled** [comment]
Thanks for all your work on this!

**Comment by aek** [comment]
Thanks to you!!

**Pull request merged**
