### PR TITLE
fix: sort CSP directives to have deterministic results - necessary specifically when asserting header values

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Mind leaving a comment why this change is not accepted?

**Comment by unrolled** [comment]
It was unclear why this change was needed. Was the goal to have the directives sorted, or to have a more explicit test?

**Comment by DeepDiver1975** [comment]
The goal is to have the directives sorted. The test was added to proof that.

Without sorting the directives the result is not deterministic and asserting header values in tests is quite hard in such a setup.

THX

**Comment by unrolled** [comment]
Ahhh I just [checked the spec](https://www.w3.org/TR/CSP3/#framework-policy) and see what you mean. I'll get the change in right away. In the future a PR description would be helpful in providing context as to why the change is needed. Thanks!

**Comment by DeepDiver1975** [comment]
Nice. I was not aware of the spec with respect to the sort order.
My intention was to have testable results.

In any case we got it sorted 🤣

**Pull request closed without merging**
